apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: artist-web
  description: The place to be, for great artists
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: production
  owner: artist-relations-team
kind: Group
metadata:
  name: artist-relations-team
  description: The infra business unit
spec:
  type: business-unit
  profile:
    displayName: artist-relations-team
    email: infrastructure@example.com
    picture: https://example.com/groups/bu-infrastructure.jpeg
  parent: ops
  children: [backstage, other]
